# Generated by Django 5.0.3 on 2024-04-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=100)),
                ('public_key', models.TextField()),
                ('passphrase', models.CharField(max_length=50)),
                ('ipaddress', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('password', models.TextField()),
                ('job_title', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=30)),
            ],
        ),
    ]
