# Generated by Django 5.0.3 on 2024-05-06 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='host',
        ),
        migrations.AddField(
            model_name='server',
            name='hostname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='server',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='server',
            name='ipaddress',
            field=models.GenericIPAddressField(default=''),
        ),
        migrations.AlterField(
            model_name='server',
            name='passphrase',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_key',
            field=models.TextField(default=''),
        ),
    ]
