# Generated by Django 5.0.3 on 2024-05-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_server_host_server_hostname_server_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='ipaddress',
            field=models.GenericIPAddressField(default='', unique=True),
        ),
    ]
